CREATE TABLE IF NOT EXISTS "1T2023"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "2T2023"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "3T2023"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "4T2023"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "1T2024"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "2T2024"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "3T2024"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "4T2024"(
	DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL MONEY,
    VL_SALDO_FINAL MONEY
);

CREATE TABLE IF NOT EXISTS "relatorio_cadop"(
	REGISTRO_ANS VARCHAR(10),
    CNPJ VARCHAR(255),
    RAZAO_SOCIAL VARCHAR(255),
    NOME_FANTASIA VARCHAR(255),
    MODALIDADE VARCHAR(255),
    LOGRADOURO VARCHAR(255),
	NUMERO VARCHAR (255),
	COMPLEMENTO VARCHAR(255),
	BAIRRO VARCHAR(255),
	CIDADE VARCHAR(255),
	UF VARCHAR(2),
	CEP VARCHAR(50),
	DDD FLOAT,
	TELEFONE FLOAT,
	FAX FLOAT,
	ENDERECO_ELETRONICO VARCHAR(255),
	REPRESENTANTE VARCHAR(255),
	CARGO_REPRESENTANTE VARCHAR(255),
	REGIAO_DE_COMERCIALIZACAO FLOAT,
	DATA_REGISTRO_ANS DATE
);

CREATE TABLE IF NOT EXISTS "dicionario_de_dados_das_operadoras_ativas"(
	NOME_DO_CAMPO VARCHAR(255),
	TIPO VARCHAR(255),
	TAMANHO VARCHAR (255),
	DESCRICAO TEXT
);


